### ISSUE TITLE
Size Problem

### ISSUE THREAD

**Issue by TheDrHell** [ThDilos/ThDilos.Fox.Expanded#1]
There is a little problem with the Fox Origin. As a Fox you are usually about 1 block tall but as soon as i get an evolution, i get a normal size again and can't get smaller again even after turning back to a normal fox...

**Comment by ThDilos** [comment]
Noted, 
This problem is likely to happens from normal fox V3.8 onwards where I removed the size restrictions.
It will be fixed in the next version of the **normal fox origin**.
Thanks for the feedback!

**Comment by TheDrHell** [comment]
Alright Thank you since it is really sad being a cute little fox and as soon as you evolve you you stay human Size, But so far i really enjoy the Origin!

**Comment by TheDrHell** [comment]
Oh and also i do have a little question still. Is the Karma Level somewhere visible or do i just have to guess it?

**Comment by ThDilos** [comment]
Can check by pressing the transform button, you'll see a meter shown above HUD.
Either positive karma towards Kitsune (The bright yellow one)
Or the negative karma towards Ninetails (The dark blue one)

**Comment by ThDilos** [comment]
Fixed in V3.8.4 Normal Fox

**Comment by TheDrHell** [comment]
Oh wow thank you a lot but now there is another problem. With the new version i now can't switch between the 4 subclasses anymore with X

**Comment by ThDilos** [comment]
The transform function is provided via the expanded mod, ideally the update in normal fox should not interfere with it.

You can try quit and re enter the world.
Or do /function thorigins:reset_all
