### ISSUE TITLE
Yūrei Form of the Kitsune

### ISSUE THREAD

**Issue by Eisteewald** [ThDilos/ThDilos.Fox.Expanded#3]
Hello. I found yesterday this mod and i really love it. But there are a few things that i don´t like.
One of them is that the Yūrei Form doesn´t go off when the Soul bar expires. I just keep phasing until i turn it off.

**Comment by ThDilos** [comment]
Thanks!
Fixed in later version.
You can go [here](https://github.com/ThDilos/ThDilos.Fox.Expanded/releases/tag/V2.0.1) to get the fixed version
