### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Eisteewald** [ThDilos/ThDilos.Fox.Expanded#4]
Hello.
I wanted to ask you, if i can tell you some ideas that i have about the Fox mods you have created?

**Comment by Eisteewald** [comment]
And do you know how to write things to one of your lables?

**Comment by ThDilos** [comment]
I have a discussion post in the datapack section of the Official Origin Discord server, ppl have been sending some good suggestions. You can check it out if uw.

**Comment by ThDilos** [comment]
As for the labels, what label is it? the github version label? the name & description of the origin? or something else?

**Comment by Eisteewald** [comment]
It´s on Issues and then on labels. there are 9. And could you give me a link or something? i can´t find the server

**Comment by ThDilos** [comment]
The discord discussion post link [here](https://discord.com/channels/734127708488859831/1208718129061175378)

You can also post the bugs & unintended features on the issue page here.

**Comment by ThDilos** [comment]
oh yeah mb
this is the invite link:
https://discord.gg/VdGgwXwWNa

**Comment by Eisteewald** [comment]
and which channel?

**Comment by ThDilos** [comment]
datapacks, there are a lot origins, foxes included

can use the search bar to find mine

**Comment by Eisteewald** [comment]
![Bild_2024-05-29_152441331](https://github.com/ThDilos/ThDilos.Fox.Expanded/assets/170609117/d659f032-b14a-4afa-ada1-28f5cccd9d21)

**Comment by Eisteewald** [comment]
Do you plan to create your own Discord server?

**Comment by ThDilos** [comment]
nah, sounds like too much work

you can use this issue page as well, whichever you find convenient
