### ISSUE TITLE
The original origins mod stuff, including the GUI, is completely broken when this mod is enabled in my modpack.

### ISSUE THREAD

**Issue by FoxxyFerris** [ThDilos/ThDilos.Fox.Expanded#5]
![{0B1DBE30-22B1-49FB-A399-DF6D4D5F7441}](https://github.com/user-attachments/assets/12708735-cd5d-450a-b04d-488b5be7f644)
![{8062645F-1F2F-46DB-9824-2B0827191987}](https://github.com/user-attachments/assets/abcf0de8-6404-4f2d-b3a9-0a28a665ecb0)

**Comment by FoxxyFerris** [comment]
Forgot to mention, i am also using MC version 1.19.2

**Comment by ThDilos** [comment]
Just tested on 1.19.1 Fabric 0.15.3. The translations are fine.
Can you share more info about this?
1. Modloader version
2. Does this issue persist if you run it with only Origin, pehkui mods Enabled
3. What is it like in the Resourcepack page

**Comment by ThDilos** [comment]
I might have located the problem and uploaded a fixed version.
See [Pre-Release](https://github.com/ThDilos/ThDilos.Fox.Expanded/releases/download/V3.0.0T/ThDilos.Fox.Expanded_V3.0.0_1.19-1.19.3.jar).
Not sure if this version fixed it.

**Comment by ThDilos** [comment]
anyways thanks for raising this bug :3

**Comment by FoxxyFerris** [comment]
> I might have located the problem and uploaded a fixed version.

![image](https://github.com/user-attachments/assets/6892c0e2-2016-4afc-aae8-f92627ed37fc)
Yes it did! Thank you so much!
